title: Zehua Zeng
description:
show_downloads: false
google_analytics:
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar-external:
  - icon: <i class="fa-regular fa-envelope"></i>
    link: mailto:fiona.zehua.zeng@gmail.com
  - icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:zehua.zeng@intel.com
  - icon: <i class="fa-brands fa-github-alt"></i>
    link: https://github.com/Zehua-Zeng
  - icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/zehuazeng/
  - icon: <i class="fa-brands fa-youtube"></i>
  - link: https://www.youtube.com/channel/UCBwabuKjUQqMnyh-Nys-X2Q/videos

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
